export const CLIENTS = [
  {
    name: "Ayesha Khan",
    role: "Brand Owner | Glow Beauty",
    category: "Canva Design",
    quote: "Tayyaba created stunning social media designs that perfectly matched my brand aesthetic. Very creative and professional work!",
    project: "Social Media Post Design",
    service: "Canva Design",
    iconImg: "/images/canva-icon.jpg",
    projectImg: "/images/canva-project.jpg",
  },
  {
    name: "Bilal Ahmed",
    role: "E-commerce Owner | Trend Mart",
    category: "AI Photo & Video + UGC Ads",
    quote: "Amazing AI-generated product visuals and UGC ads brought our products to life and gave our campaign a much more professional look.",
    project: "UGC Ad Creative",
    service: "AI Photo & Video + UGC Ads",
    iconImg: "/images/ai-icon.jpg",
    projectImg: "/images/ai-project.jpg",
  },
  {
    name: "Sana Malik",
    role: "Marketing Manager | FitLife Studio",
    category: "Social Media Marketing",
    quote: "Tayyaba handled our social media marketing brilliantly. Engagement increased and our overall page growth was incredible!",
    project: "Social Media Campaign",
    service: "Social Media Marketing",
    iconImg: "/images/social-icon.jpg",
    projectImg: "/images/social-project.jpg",
  },
  {
    name: "Omer Farooq",
    role: "CEO | TechNova Solutions",
    category: "2D & 3D Animation",
    quote: "The 3D product animation was beyond our expectations. It helped us present our product in a much more professional way.",
    project: "3D Product Animation",
    service: "2D & 3D Animation",
    iconImg: "/images/anim-icon.jpg",
    projectImg: "/images/anim-project.jpg",
  },
  {
    name: "Dr. Hina Raza",
    role: "Educator | Learn & Grow Academy",
    category: "Whiteboard Videos",
    quote: "The whiteboard explainer made our training content easy to understand and highly engaging for our students.",
    project: "Educational Whiteboard Video",
    service: "Whiteboard Videos",
    iconImg: "/images/board-icon.png",
    projectImg: "/images/board-project.jpg",
  },
  {
    name: "Zain Ali",
    role: "Content Creator",
    category: "Reels & Short Video Editing",
    quote: "The reels and shorts edited by Tayyaba are clean, trendy and highly engaging. The content looks professional and performs well.",
    project: "Instagram Reels Editing",
    service: "Reels & Short Video Editing",
    iconImg: "/images/reels-icon.jpg",
    projectImg: "/images/reels-project.jpg",
  },
];
