export const SKILLS = [
  {
    key: "canva",
    name: "Canva Design",
    jobTitles: "Canva Graphic Designer · Social Media Graphic Designer",
    tagline: "Scroll-stopping social posts, flyers and ad creatives.",
    services: ["Social Media Posts", "Flyers", "Banners", "Ads", "Thumbnails", "Marketing Designs"],
    tools: ["Canva"],
    grad: "linear-gradient(135deg,#14C4C4,#7B61FF)",
    iconImg: "/images/canva-icon.jpg",
  },
  {
    key: "ai",
    name: "AI Photo & Video + UGC Ad Generation",
    jobTitles: "AI Content Creator · AI Photo & Video Editor · UGC Ad Creator",
    tagline: "AI-powered visuals and UGC ads that feel authentic.",
    services: ["AI Photo Generation", "AI Photo Editing", "AI Video Generation", "AI Video Editing", "UGC Ad Generation", "AI-Powered Social Content"],
    tools: ["AI image generation tools", "AI video tools", "Photo & video editing tools"],
    grad: "linear-gradient(135deg,#EC4899,#8B5CF6)",
    iconImg: "/images/ai-icon.jpg",
  },
  {
    key: "social",
    name: "Social Media Marketing",
    jobTitles: "Social Media Manager · Marketing Specialist · Content Strategist",
    tagline: "Growing pages with strategy, not guesswork.",
    services: ["Facebook Marketing", "Instagram Marketing", "Content Strategy", "Social Media Management", "Engagement Strategy", "Promotional Campaigns"],
    tools: ["Facebook", "Instagram", "Social media management tools"],
    grad: "linear-gradient(135deg,#3B82F6,#22D3EE)",
    iconImg: "/images/social-icon.jpg",
  },
  {
    key: "anim",
    name: "2D & 3D Animation Videos",
    jobTitles: "2D/3D Animator · Motion Graphics Designer · Explainer Video Creator",
    tagline: "Product stories told through motion.",
    services: ["2D Animation", "3D Animation", "Explainer Videos", "Character Animation", "Product Animation", "Motion Graphics"],
    tools: ["After Effects", "3D animation software", "Motion graphics tools"],
    grad: "linear-gradient(135deg,#8B5CF6,#6D28D9)",
    iconImg: "/images/anim-icon.jpg",
  },
  {
    key: "board",
    name: "Whiteboard Videos",
    jobTitles: "Whiteboard Animation Creator · Explainer & Educational Video Creator",
    tagline: "Simple sketches that explain complex ideas.",
    services: ["Whiteboard Animation", "Business Explainer Videos", "Educational Videos", "Presentation Videos", "Storytelling Videos"],
    tools: ["Whiteboard animation tools", "Presentation tools"],
    grad: "linear-gradient(135deg,#F5B942,#EC4899)",
    iconImg: "/images/board-icon.png",
  },
  {
    key: "reels",
    name: "Reels & Short Video Editing",
    jobTitles: "Reels Editor · Short-Form Video Editor · TikTok Video Editor",
    tagline: "Fast-paced edits built for the scroll.",
    services: ["Instagram Reels", "YouTube Shorts", "TikTok Videos", "Facebook Reels", "Short-form Editing", "Social Video Content"],
    tools: ["Video editing software", "Social media editing tools"],
    grad: "linear-gradient(135deg,#F97316,#EA580C)",
    iconImg: "/images/reels-icon.jpg",
  },
];
